pipelines:
  - name: check
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: post-commit
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        event: ref-updated
        ref: master

jobs:
  - name: ^.*-merge$
    failure-message: Unable to merge change, please rebase and try again.

projects:
  - name: baserock/baserock/definitions
    check:
      - build:
        - build_test
    post:
      - build:
        - build_test

  - name: baserock/baserock/morph
    post-commit:
      - foobar
