# System configuration for Baserock database server.
#
# This Ansible playbook expects to be run on a Fedora 21 Cloud image.
---
- hosts: database-mariadb
  gather_facts: False
  sudo: True
  tasks:
  - name: enable persistant journal
    shell: mkdir /var/log/journal
    args:
      creates: /var/log/journal

  - name: install lvm2 tools
    yum: name=lvm2 state=latest

  - name: install MariaDB
    yum: name={{ item }} state=latest
    with_items:
        - mariadb
        - mariadb-server
        - MySQL-python

  - name: install libselinux-python, so Ansible can control selinux
    yum: name=libselinux-python state=latest

  - name: disable SELinux on subsequent boots
    selinux: state=disabled

  - name: disable SELinux on current boot
    command: setenforce 0
