# Instance configuration for Baserock database server.
#
# This script expects a volume to be available at /dev/vdb.
---
- hosts: database-mariadb
  gather_facts: False
  sudo: yes
  tasks:
    - include: ../tasks/create-data-volume.yml lv_name=database lv_size=25g mountpoint=/var/lib/mysql

    - name: ensure mysql user owns /var/lib/mysql
      file: path=/var/lib/mysql owner=mysql group=mysql mode=600 state=directory

    - name: start MariaDB service
      service: name=mariadb state=started
