# This Makefile is a developer convenience only!!
#
# If you are developing the Mason setup scripts, you can use 'make install'
# to overwrite the ones in your machine.


install:
	(cd .. && ./mason.configure /)
