---
- hosts: localhost
  tasks:
  - name: enable persistant journal
    shell: mkdir /var/log/journal
    args:
      creates: /var/log/journal

  - name: install Cherokee web server
    yum: name=cherokee state=latest

  - name: install PIP package manager
    yum: name=python-pip state=latest

  - name: install uWSGI application container server and Python plugin
    yum: name=uwsgi-plugin-python state=latest

  - name: install Django
    pip: name=django

  # This is a fork of django-registration which supports Django 1.7.
  # Source: https://github.com/macropin/django-registration
  # The original django-registration (which seems to be abandoned) lives at:
  # https://bitbucket.org/ubernostrum/django-registration/
  - name: install django-registration-redux
    pip: name=django-registration-redux

  - name: install python-openid
    pip: name=python-openid

  - name: install Cherokee configuration
    shell: ln -sf /srv/baserock_openid_provider/cherokee.conf /etc/cherokee/cherokee.conf
