---
- hosts: localhost
  tasks:
  - name: install PIP package manager
    yum: name=python-pip state=latest

  # django-registration doesn't yet work with Django 1.7. See:
  # https://stackoverflow.com/questions/25537905/django-1-7-throws-django-core-exceptions-appregistrynotready-models-arent-load
  - name: install Django
    pip: name=django version=1.6.8

  - name: install django-registration
    pip: name=django-registration

  - name: install python-openid
    pip: name=python-openid

