---
- hosts: localhost
  tasks:
  - name: install PIP package manager
    yum: name=python-pip state=latest

  - name: install Django
    pip: name=django

  # This is a fork of django-registration which supports Django 1.7.
  # Source: https://github.com/macropin/django-registration
  # The original django-registration (which seems to be abandoned) lives at:
  # https://bitbucket.org/ubernostrum/django-registration/
  - name: install django-registration-redux
    pip: name=django-registration-redux

  - name: install python-openid
    pip: name=python-openid

