pipelines:
  - name: check-change
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
  - name: post-commit
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(!?refs/).*$

jobs:
  - name: ^.*-merge$
    failure-message: Unable to merge change, please rebase and try again.

projects:
  - name: baserock/baserock/definitions
    check-change:
      - build:
        - build_test
    post-commit:
      - build:
        - build_test
