---
- hosts: localhost
  vars_files:
  - "/etc/openstack/neutron.conf"
  tasks:

  - name: Create the neutron user.
    user:
        name: neutron
        comment: Openstack Neutron Daemons
        shell: /sbin/nologin
        home: /var/lib/neutron

  - name: Create the /var folders for neutron
    file:
        path: "{{ item }}"
        state: directory
        owner: neutron
        group: neutron
    with_items:
    - /var/run/neutron
    - /var/lock/neutron
    - /var/log/neutron

  - name: Get service tenant id needed in neutron.conf
    shell: |
           keystone \
               --os-endpoint http://{{ CONTROLLER_HOST_ADDRESS|quote }}:35357/v2.0 \
               --os-token {{ KEYSTONE_TEMPORARY_ADMIN_TOKEN|quote }} \
               tenant-get service | grep id | tr -d " " | cut -d"|" -f3
    register: tenant_service_id

  - set_fact:
        SERVICE_TENANT_ID: "{{ tenant_service_id.stdout }}"

  - name: Create the directories needed for Neutron configuration files.
    file:
        path: /etc/{{ item }}
        state: directory
    with_lines:
    - cd /usr/share/openstack &&  find neutron -type d

  - name: Add configuration needed for neutron using templates
    template:
        src: /usr/share/openstack/{{ item }}
        dest: /etc/{{ item }}
    with_lines:
    - cd /usr/share/openstack && find neutron -type f
